### ISSUE TITLE
ASM version not working?

### ISSUE THREAD

**Issue by Potherca** [Francesco149/nolibc-httpd#4]
When I run the build, everything works as expected, but when I try the ASM version I only get usage information:

```sh
$ ./asm.sh
$ ./httpd 8080 test.html
usage: ./httpd port file
$ echo $?
1
```

Am I missing something, or is the ASM version broken?

**Comment by Francesco149** [comment]
hey, I know it's been 3 years and I never replied to this. I don't know if this will fix your issue since the asm binary has always worked for me, but I updated the asm version to reflect latest code changes so if that still happens and you are still interested in fixing, reopen the issue. it might be the stripped down elf header causing issues on some machines, not sure

**Comment by Potherca** [comment]
Not sure if it was the code update or changes to my local machine, but the ASM version works fine currently:

```sh
git clone https://github.com/Francesco149/nolibc-httpd.git /tmp/nolibc-httpd \
    && cd $_ \
    && ./asm.sh \
    && chmod +x httpd \
    && ./httpd 8080 test.html
```

Thanks for the response!
